import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import AppBgImg from "@/Component/BgImage/BgImage";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PCSO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppBgImg />
        {children}</body>
    </html>
  );
}
